version: '3'
networks:
  grafana:
    internal: true
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./data:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana