Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.provider "virtualbox" do |vb|
        vb.name = "Prometheus"
    end
    prometheus.vm.network "public_network", ip: "192.168.1.50"
    prometheus.vm.network "forwarded_port", guest: 9090, host: 9090
    prometheus.vm.synced_folder "./configs/keys", "/configs/keys"
    prometheus.vm.synced_folder "../docker-compose/prometheus", "/opt/prometheus/"
    prometheus.vm.synced_folder ".", "/vagrant", disabled: true
    prometheus.vm.provision "shell", path: "./scripts/install_docker.sh"
    prometheus.vm.provision "shell",
      inline: "cat /configs/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.define "grafana" do |grafana|
    grafana.vm.provider "virtualbox" do |vb|
        vb.name = "Grafana"
    end
    grafana.vm.network "public_network", ip: "192.168.1.51"
    grafana.vm.network "forwarded_port", guest: 3000, host: 3000
    grafana.vm.synced_folder "./configs/keys", "/configs/keys"
    grafana.vm.synced_folder "../docker-compose/grafana", "/opt/grafana/"
    grafana.vm.synced_folder ".", "/vagrant", disabled: true
    grafana.vm.provision "shell", path: "./scripts/install_docker.sh"
    grafana.vm.provision "shell",
      inline: "cat /configs/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.provider "virtualbox" do |vb|
        vb.name = "Ansible"
    end
    ansible.vm.network "public_network", ip: "192.168.1.52"
    ansible.vm.synced_folder "./configs", "/configs"
    ansible.vm.synced_folder ".", "/vagrant", disabled: true
    ansible.vm.provision "shell", path: "./scripts/install_ansible.sh"
    ansible.vm.provision "shell",
      inline: "cat /configs/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
    ansible.vm.provision "shell",
      inline: "cp /configs/keys/id_rsa /home/vagrant/ && \
      chmod 600 /home/vagrant/id_rsa && \
      chown vagrant:vagrant id_rsa"
    ansible.vm.provision "shell", 
      inline: "ansible-playbook -i /configs/ansible/hosts /configs/ansible/playbook.yml"
  end
end
